openapi: 3.0.1
info:
  title: hotelsAPI
  description: API Definition of hotelsAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/hotels
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
    delete:
      responses:
        default:
          description: Default response
    patch:
      responses:
        default:
          description: Default response
