openapi: 3.0.1
info:
  title: reservationsAPI
  description: API Definition of reservationsAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/reservations
paths:
  /:
    get:
      responses:
        default:
          description: Default response
